import { lazy } from "react";
import { CategoryInfo, ToolDefinition } from "./types/tool";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "text",
    name: "文本工具",
    description: "大写金额转换、文本处理等",
    iconName: "FileText",
  },
  {
    id: "image",
    name: "图片工具",
    description: "图片压缩、格式转换、颜色拾取等前端图形处理",
    iconName: "Image",
  },
  {
    id: "crypto",
    name: "加密工具",
    description: "Base64 编解码、哈希散列等安全计算",
    iconName: "KeyRound",
  },
];

export const TOOLS: ToolDefinition[] = [
  {
    id: "currency-to-chinese",
    name: "大写金额转换",
    description: "将阿拉伯数字金额转换为中文大写金额（财务标准汉字）",
    category: "text",
    tags: ["金额", "大写", "人民币", "财务", "数字转汉字"],
    iconName: "Coins",
    status: "stable",
    component: lazy(() => import("./tools/text/CurrencyToChinese")),
  },
  {
    id: "json-formatter",
    name: "JSON 格式化 / 校验",
    description: "JSON 语法校验、精准错误定位、树形美化、Key 键排序与单行压缩",
    category: "text",
    tags: ["json", "格式化", "美化", "压缩", "校验", "minify", "beautify"],
    iconName: "Braces",
    status: "stable",
    component: lazy(() => import("./tools/text/JsonFormatter")),
  },
  {
    id: "text-diff",
    name: "文本比对",
    description: "支持双栏与合并模式对比两段文本的行级与字符级差异",
    category: "text",
    tags: ["diff", "文本差异", "对比", "代码比对", "找不同"],
    iconName: "GitCompare",
    status: "stable",
    component: lazy(() => import("./tools/text/TextDiff")),
  },
  {
    id: "regex-tester",
    name: "正则表达式测试",
    description: "实时正则匹配高亮、捕获组分析、正则替换与常用表达式库",
    category: "text",
    tags: ["regex", "正则", "正则表达式", "replace", "匹配", "regexp"],
    iconName: "Regex",
    status: "stable",
    component: lazy(() => import("./tools/text/RegexTester")),
  },
  {
    id: "text-analyzer",
    name: "字数统计与排版",
    description: "实时中英文字数统计、段落阅读时间预估、中英文空格美化（盘古排版）与全半角转换",
    category: "text",
    tags: ["字数", "字数统计", "排版", "中英文空格", "盘古排版", "阅读时长", "全角半角"],
    iconName: "AlignLeft",
    status: "stable",
    component: lazy(() => import("./tools/text/TextAnalyzer")),
  },
  {
    id: "image-compressor",
    name: "图片压缩",
    description: "纯本地 Canvas 调整质量与尺寸，大幅减小图片体积",
    category: "image",
    tags: ["压缩", "图片", "tinypng", "webp", "jpg"],
    iconName: "Minimize2",
    status: "stable",
    component: lazy(() => import("./tools/image/ImageCompressor")),
  },
  {
    id: "image-converter",
    name: "图片格式转换",
    description: "支持 PNG、JPG、WebP 等多格式批量互转与一键导出",
    category: "image",
    tags: ["转换", "png", "webp", "jpg", "批量格式转换"],
    iconName: "RefreshCw",
    status: "stable",
    component: lazy(() => import("./tools/image/ImageConverter")),
  },
  {
    id: "color-picker",
    name: "颜色拾取器",
    description: "高倍放大镜精准拾色，支持屏幕取色及 HEX/RGB/HSL/CMYK 多格式换算",
    category: "image",
    tags: ["取色", "吸管", "颜色拾取", "hex", "rgb", "hsl", "cmyk", "配色"],
    iconName: "Pipette",
    status: "stable",
    component: lazy(() => import("./tools/image/ColorPicker")),
  },
  {
    id: "qrcode-tool",
    name: "二维码生成与识别",
    description: "高清二维码生成、自定义配色与 Logo 嵌入，支持本地图片解析",
    category: "image",
    tags: ["qrcode", "二维码", "生成二维码", "扫描", "解析二维码", "识别"],
    iconName: "QrCode",
    status: "stable",
    component: lazy(() => import("./tools/image/QrCodeTool")),
  },
  {
    id: "base64-converter",
    name: "Base64 编解码",
    description: "支持 UTF-8 文本编码/解码、URL-Safe 安全模式与文件转 Base64 DataURI",
    category: "crypto",
    tags: ["base64", "编码", "解码", "datauri", "url-safe", "加密"],
    iconName: "Binary",
    status: "stable",
    component: lazy(() => import("./tools/crypto/Base64Converter")),
  },
  {
    id: "hash-calculator",
    name: "哈希散列计算",
    description: "聚合 MD5、SHA-1、SHA-256、SHA-512、SHA-3、RIPEMD160 等散列与 HMAC 计算",
    category: "crypto",
    tags: ["hash", "md5", "sha256", "sha512", "sha1", "hmac", "散列", "校验码", "摘要"],
    iconName: "Hash",
    status: "stable",
    component: lazy(() => import("./tools/crypto/HashCalculator")),
  },
  {
    id: "symmetric-crypto",
    name: "对称加解密",
    description: "支持 AES、DES、3DES、RC4、Rabbit 与 SM4 对称加解密",
    category: "crypto",
    tags: ["aes", "des", "3des", "rc4", "sm4", "加密", "解密", "crypto", "cbc", "ecb"],
    iconName: "Lock",
    status: "stable",
    component: lazy(() => import("./tools/crypto/SymmetricCrypto")),
  },
  {
    id: "asymmetric-crypto",
    name: "非对称加解密",
    description: "支持 RSA (2048-bit) 与 SM2 密钥对生成、公钥加密与私钥解密",
    category: "crypto",
    tags: ["rsa", "sm2", "非对称", "公钥", "私钥", "加密", "解密", "密钥对", "keypair"],
    iconName: "KeyRound",
    status: "stable",
    component: lazy(() => import("./tools/crypto/AsymmetricCrypto")),
  },
  {
    id: "password-generator",
    name: "密码生成器",
    description: "基于密码学加密安全随机数生成高强度随机密码，支持批量与强度估算",
    category: "crypto",
    tags: ["密码", "密码生成", "随机密码", "password", "强密码", "安全密码"],
    iconName: "KeyRound",
    status: "stable",
    component: lazy(() => import("./tools/crypto/PasswordGenerator")),
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}
