import { lazy } from "react";
import { CategoryInfo, ToolDefinition } from "./types/tool";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "dev",
    name: "编码开发",
    description: "JSON、SQL、XML 格式化，正则测试，HTTP 调试等开发常用工具",
    iconName: "Code2",
  },
  {
    id: "text",
    name: "文本处理",
    description: "文本比对、字数统计、去重清洗、简繁拼音与 Markdown 编辑",
    iconName: "FileText",
  },
  {
    id: "convert",
    name: "编码转换",
    description: "Base64、进制、URL、Unicode、摩斯电码与单位换算",
    iconName: "ArrowLeftRight",
  },
  {
    id: "image",
    name: "图片处理",
    description: "图片压缩、格式转换、裁剪、水印、EXIF 与 Favicon 生成",
    iconName: "Image",
  },
  {
    id: "design",
    name: "图形设计",
    description: "颜色拾取、CSS 渐变、二维码、条形码、SVG 与代码截图",
    iconName: "Palette",
  },
  {
    id: "crypto",
    name: "加密安全",
    description: "哈希散列、对称与非对称加解密、密码与 UUID 生成",
    iconName: "ShieldCheck",
  },
  {
    id: "media",
    name: "多媒体",
    description: "音频剪辑、视频转 GIF 与屏幕显示检测",
    iconName: "Film",
  },
];

export const TOOLS: ToolDefinition[] = [
  // ── 1. 编码开发 (dev) ──
  {
    id: "json-formatter",
    name: "JSON 格式化",
    description: "JSON 语法校验、精准错误定位、树形美化、Key 键排序与单行压缩",
    category: "dev",
    tags: ["json", "格式化", "美化", "压缩", "校验", "minify", "beautify"],
    iconName: "Braces",
    status: "stable",
    component: lazy(() => import("./tools/dev/JsonFormatter")),
  },
  {
    id: "regex-tester",
    name: "正则测试",
    description: "实时正则匹配高亮、捕获组分析、正则替换与常用表达式库",
    category: "dev",
    tags: ["regex", "正则", "正则表达式", "replace", "匹配", "regexp"],
    iconName: "Regex",
    status: "stable",
    component: lazy(() => import("./tools/dev/RegexTester")),
  },
  {
    id: "regex-railroad",
    name: "正则铁路图",
    description: "将正则表达式分解为直观清晰的语法节点铁路流程图，看懂匹配逻辑",
    category: "dev",
    tags: ["regex", "铁路图", "流程图", "railroad", "正则可视化", "语法树"],
    iconName: "GitBranch",
    status: "stable",
    component: lazy(() => import("./tools/dev/RegexRailroad")),
  },
  {
    id: "yaml-converter",
    name: "YAML / JSON 互转",
    description: "配置文件双向极速转换、语法校验排错与格式化一键导出",
    category: "dev",
    tags: ["yaml", "json", "yml", "yaml转json", "json转yaml", "配置转换"],
    iconName: "FileCode2",
    status: "stable",
    component: lazy(() => import("./tools/dev/YamlConverter")),
  },
  {
    id: "xml-formatter",
    name: "XML 格式化",
    description: "XML 树状节点换行缩进排版美化、DOMParser 语法错误定位与单行压缩",
    category: "dev",
    tags: ["xml", "xml格式化", "xml美化", "xml校验", "domparser", "minify"],
    iconName: "CodeXml",
    status: "stable",
    component: lazy(() => import("./tools/dev/XmlFormatter")),
  },
  {
    id: "sql-formatter",
    name: "SQL 格式化",
    description: "多数据库方言 SQL 语法换行缩进美化、关键字大写与单行压缩",
    category: "dev",
    tags: ["sql", "sql格式化", "mysql", "postgresql", "oracle", "美化", "minify"],
    iconName: "Database",
    status: "stable",
    component: lazy(() => import("./tools/dev/SqlFormatter")),
  },
  {
    id: "json-to-ts-converter",
    name: "JSON 转 TypeScript",
    description: "自动递归推导 JSON 嵌套对象与数组类型，生成标准 Interface / Type 声明",
    category: "dev",
    tags: ["json", "typescript", "ts", "json2ts", "类型推导", "interface"],
    iconName: "FileCode2",
    status: "stable",
    component: lazy(() => import("./tools/dev/JsonToTsConverter")),
  },
  {
    id: "curl-converter",
    name: "cURL 转代码",
    description: "一键将 cURL 命令转换为 Fetch、Axios、Python Requests、Go 等语言代码",
    category: "dev",
    tags: ["curl", "curl转代码", "fetch", "axios", "python", "requests", "api调用"],
    iconName: "Terminal",
    status: "stable",
    component: lazy(() => import("./tools/dev/CurlConverter")),
  },
  {
    id: "http-request-tester",
    name: "HTTP 接口调试",
    description: "支持 GET/POST 在线发包测试、请求头与 JSON 体编辑、响应耗时与状态查看",
    category: "dev",
    tags: ["http", "api", "postman", "fetch", "网络请求", "接口测试"],
    iconName: "Send",
    status: "stable",
    component: lazy(() => import("./tools/dev/HttpRequestTester")),
  },
  {
    id: "http-status-lookup",
    name: "HTTP 状态码速查",
    description: "RFC 标准 HTTP 状态码字典、语义解析与前后端排错联调参考指南",
    category: "dev",
    tags: ["http", "状态码", "status code", "200", "404", "500", "502", "rfc", "排错"],
    iconName: "Activity",
    status: "stable",
    component: lazy(() => import("./tools/dev/HttpStatusLookup")),
  },
  {
    id: "jwt-debugger",
    name: "JWT 解析验证",
    description: "JSON Web Token 头部与载荷极速解析、过期时间智能计算与 HS256 签名校验",
    category: "dev",
    tags: ["jwt", "token", "json web token", "auth", "decode", "hs256", "鉴权"],
    iconName: "FileCode2",
    status: "stable",
    component: lazy(() => import("./tools/dev/JwtDebugger")),
  },
  {
    id: "cron-parser-tool",
    name: "Cron 表达式解析",
    description: "Cron 定时任务表达式中文语义翻译、未来执行时间推演与常用规则速查",
    category: "dev",
    tags: ["cron", "crontab", "定时任务", "cron表达式", "计划任务", "执行时间"],
    iconName: "Timer",
    status: "stable",
    component: lazy(() => import("./tools/dev/CronParserTool")),
  },
  {
    id: "git-command-generator",
    name: "Git 命令生成",
    description: "解决撤销提交、历史修改、分支合并、储藏与冲突还原等常见 Git 场景",
    category: "dev",
    tags: ["git", "git命令", "版本控制", "撤销commit", "stash", "rebase", "分支管理"],
    iconName: "GitBranch",
    status: "stable",
    component: lazy(() => import("./tools/dev/GitCommandGenerator")),
  },
  {
    id: "ua-parser-tool",
    name: "User-Agent 解析",
    description: "精准解析客户端浏览器内核版本、操作系统、设备型号与网络爬虫标识",
    category: "dev",
    tags: ["useragent", "ua", "浏览器", "操作系统", "设备检测", "爬虫标识"],
    iconName: "Monitor",
    status: "stable",
    component: lazy(() => import("./tools/dev/UaParserTool")),
  },
  {
    id: "cidr-calculator",
    name: "IP / CIDR 计算",
    description: "IPv4 网络地址、广播地址、可用主机范围、通配符反码与子网对照速查",
    category: "dev",
    tags: ["ip", "cidr", "子网掩码", "网段计算", "subnet", "ipv4", "广播地址"],
    iconName: "Network",
    status: "stable",
    component: lazy(() => import("./tools/dev/CidrCalculator")),
  },

  // ── 2. 文本处理 (text) ──
  {
    id: "text-diff",
    name: "文本比对",
    description: "支持双栏与合并模式对比两段文本的行级与字符级差异",
    category: "text",
    tags: ["diff", "文本差异", "对比", "代码比对", "找不同"],
    iconName: "GitCompare",
    status: "stable",
    component: lazy(() => import("./tools/text/TextDiff")),
  },
  {
    id: "text-analyzer",
    name: "字数统计与排版",
    description: "实时中英文字数统计、段落阅读时间预估、中英文空格美化（盘古排版）与全半角转换",
    category: "text",
    tags: ["字数", "字数统计", "排版", "中英文空格", "盘古排版", "阅读时长", "全角半角"],
    iconName: "AlignLeft",
    status: "stable",
    component: lazy(() => import("./tools/text/TextAnalyzer")),
  },
  {
    id: "text-deduplicator",
    name: "文本去重与清洗",
    description: "按行去重、空白与标签清洗、多规则排序、前后缀添加与驼峰下划线风格转换",
    category: "text",
    tags: ["去重", "文本清洗", "排序", "驼峰转换", "下划线", "行号", "dedup", "trim"],
    iconName: "ListFilter",
    status: "stable",
    component: lazy(() => import("./tools/text/TextDeduplicator")),
  },
  {
    id: "currency-to-chinese",
    name: "大写金额转换",
    description: "将阿拉伯数字金额转换为中文大写金额（财务标准汉字）",
    category: "text",
    tags: ["金额", "大写", "人民币", "财务", "数字转汉字"],
    iconName: "Coins",
    status: "stable",
    component: lazy(() => import("./tools/text/CurrencyToChinese")),
  },
  {
    id: "pinyin-and-simplified-converter",
    name: "简繁拼音转换",
    description: "简体与繁体中文实时双向互转、带声调汉语拼音生成、首字母与注音排版",
    category: "text",
    tags: ["拼音", "繁体", "简体", "简繁转换", "汉字注音", "ruby", "pinyin"],
    iconName: "Languages",
    status: "stable",
    component: lazy(() => import("./tools/text/PinyinAndSimplifiedConverter")),
  },
  {
    id: "markdown-editor",
    name: "Markdown 编辑器",
    description: "GFM 语法支持、双栏实时渲染排版、字数统计与导出 HTML/Markdown",
    category: "text",
    tags: ["markdown", "md", "预览", "富文本", "gfm", "排版", "html导出"],
    iconName: "FileText",
    status: "stable",
    component: lazy(() => import("./tools/text/MarkdownEditor")),
  },
  {
    id: "mock-data-generator",
    name: "Mock 数据生成",
    description: "自定义表结构批量生成姓名、手机号、二代身份证、邮箱等 Mock 测试数据",
    category: "text",
    tags: ["mock", "假数据", "测试数据", "随机数据", "身份证生成", "手机号生成", "faker"],
    iconName: "TableProperties",
    status: "stable",
    component: lazy(() => import("./tools/text/MockDataGenerator")),
  },
  {
    id: "ascii-text-generator",
    name: "ASCII 艺术字生成",
    description: "英文字符转换为大型 ASCII 字符画横幅，支持各类代码头注释封装",
    category: "text",
    tags: ["ascii", "字符画", "banner", "figlet", "艺术字", "注释banner"],
    iconName: "Type",
    status: "stable",
    component: lazy(() => import("./tools/text/AsciiTextGenerator")),
  },
  {
    id: "sensitive-word-filter",
    name: "敏感词检测",
    description: "纯本地离线检测广告法极限词、违规营销引流词与低俗词汇，支持高亮与一键脱敏",
    category: "text",
    tags: ["敏感词", "违禁词", "广告法", "极限词", "内容审查", "脱敏", "过滤"],
    iconName: "ShieldAlert",
    status: "stable",
    component: lazy(() => import("./tools/text/SensitiveWordFilter")),
  },

  // ── 3. 编码转换 (convert) ──
  {
    id: "base64-converter",
    name: "Base64 编解码",
    description: "支持 UTF-8 文本编码/解码、URL-Safe 安全模式与文件转 Base64 DataURI",
    category: "convert",
    tags: ["base64", "编码", "解码", "datauri", "url-safe", "加密"],
    iconName: "Binary",
    status: "stable",
    component: lazy(() => import("./tools/convert/Base64Converter")),
  },
  {
    id: "radix-converter",
    name: "进制转换",
    description: "支持 2、8、10、16、32、36、64 进制任意数值高精度大数互转",
    category: "convert",
    tags: ["进制", "进制转换", "二进制", "十进制", "十六进制", "base64", "hex", "bin", "oct"],
    iconName: "ArrowLeftRight",
    status: "stable",
    component: lazy(() => import("./tools/convert/RadixConverter")),
  },
  {
    id: "url-parser",
    name: "URL 解析与编解码",
    description: "URL 路由分解、Query 参数可视化表格增删改查、URI 编解码与 JSON 互转",
    category: "convert",
    tags: ["url", "query", "urlencode", "urldecode", "参数解析", "searchparams", "uri"],
    iconName: "Link",
    status: "stable",
    component: lazy(() => import("./tools/convert/UrlParser")),
  },
  {
    id: "html-entity-converter",
    name: "HTML 实体编解码",
    description: "特殊字符实体转义、Unicode 十进制与十六进制实体互转与 XSS 过滤",
    category: "convert",
    tags: ["html", "xml", "实体编码", "转义", "entity", "escape", "unescape"],
    iconName: "CodeXml",
    status: "stable",
    component: lazy(() => import("./tools/convert/HtmlEntityConverter")),
  },
  {
    id: "unicode-converter",
    name: "Unicode 编码互转",
    description: "汉字与 \\\\u4e2d\\\\u6587、HTML 实体、U+码位及 UTF-8 字节十六进制多格式双向转换",
    category: "convert",
    tags: ["unicode", "编码转换", "unicode转中文", "utf8", "hex", "字符编码"],
    iconName: "Binary",
    status: "stable",
    component: lazy(() => import("./tools/convert/UnicodeConverter")),
  },
  {
    id: "morse-code-tool",
    name: "摩斯电码",
    description: "国际标准摩尔斯电码实时双向翻译、支持 Web Audio 电报音频发声播放",
    category: "convert",
    tags: ["摩斯密码", "morse", "电报", "滴答声", "morsecode", "sos"],
    iconName: "Radio",
    status: "stable",
    component: lazy(() => import("./tools/convert/MorseCodeTool")),
  },
  {
    id: "unit-converter",
    name: "单位换算",
    description: "数据存储、长度、面积、重量、温度、时间、速度与压力全量联动换算",
    category: "convert",
    tags: ["单位换算", "存储换算", "mb转gb", "长度换算", "温度换算", "重量换算", "unit"],
    iconName: "Scale",
    status: "stable",
    component: lazy(() => import("./tools/convert/UnitConverter")),
  },
  {
    id: "timestamp-converter",
    name: "时间戳转换",
    description: "Unix 秒与毫秒时间戳互转、本地与 UTC 标准时间解析、全球主要时区实时对照",
    category: "convert",
    tags: ["时间戳", "timestamp", "unix", "时区", "utc", "时间转换", "date"],
    iconName: "Clock",
    status: "stable",
    component: lazy(() => import("./tools/convert/TimestampConverter")),
  },

  // ── 4. 图片处理 (image) ──
  {
    id: "image-compressor",
    name: "图片压缩",
    description: "纯本地 Canvas 调整质量与尺寸，大幅减小图片体积",
    category: "image",
    tags: ["压缩", "图片", "tinypng", "webp", "jpg"],
    iconName: "Minimize2",
    status: "stable",
    component: lazy(() => import("./tools/image/ImageCompressor")),
  },
  {
    id: "image-converter",
    name: "图片格式转换",
    description: "支持 PNG、JPG、WebP 等多格式批量互转与一键导出",
    category: "image",
    tags: ["转换", "png", "webp", "jpg", "批量格式转换"],
    iconName: "RefreshCw",
    status: "stable",
    component: lazy(() => import("./tools/image/ImageConverter")),
  },
  {
    id: "image-cropper",
    name: "图片裁剪",
    description: "多比例自由裁剪、平滑圆角/圆形头像裁切与朋友圈 3x3 九宫格切图导出",
    category: "image",
    tags: ["裁剪", "切图", "圆角", "圆形头像", "九宫格", "crop", "朋友圈切图"],
    iconName: "Crop",
    status: "stable",
    component: lazy(() => import("./tools/image/ImageCropper")),
  },
  {
    id: "image-watermark",
    name: "图片水印",
    description: "证件照防盗用全屏平铺水印、方位水印、旋转角度与透明度调节",
    category: "image",
    tags: ["水印", "图片水印", "防盗图", "证件水印", "watermark", "平铺水印"],
    iconName: "Stamp",
    status: "stable",
    component: lazy(() => import("./tools/image/ImageWatermark")),
  },
  {
    id: "exif-tool",
    name: "EXIF 查看与清除",
    description: "读取照片拍摄相机、镜头参数、GPS 坐标，并支持一键脱敏擦除隐私元数据",
    category: "image",
    tags: ["exif", "元数据", "gps定位", "相机参数", "照片信息", "清除exif", "脱敏"],
    iconName: "Camera",
    status: "stable",
    component: lazy(() => import("./tools/image/ExifTool")),
  },
  {
    id: "placeholder-generator",
    name: "占位图生成",
    description: "快速生成任意规格的网页开发占位图，支持对角线与 PNG/SVG 导出",
    category: "image",
    tags: ["占位图", "placeholder", "尺寸图", "开发占位", "假图生成", "svg占位"],
    iconName: "Image",
    status: "stable",
    component: lazy(() => import("./tools/image/PlaceholderGenerator")),
  },
  {
    id: "favicon-generator",
    name: "Favicon 生成",
    description: "将图片转换为 16~512px 全规格 PNG 图标与标准二进制多尺寸 .ico 格式",
    category: "image",
    tags: ["favicon", "ico", "网站图标", "app-icon", "ico生成", "图标制作"],
    iconName: "Sparkles",
    status: "stable",
    component: lazy(() => import("./tools/image/FaviconGenerator")),
  },

  // ── 5. 图形设计 (design) ──
  {
    id: "color-picker",
    name: "颜色拾取器",
    description: "高倍放大镜精准拾色，支持屏幕取色及 HEX/RGB/HSL/CMYK 多格式换算",
    category: "design",
    tags: ["取色", "吸管", "颜色拾取", "hex", "rgb", "hsl", "cmyk", "配色"],
    iconName: "Pipette",
    status: "stable",
    component: lazy(() => import("./tools/design/ColorPicker")),
  },
  {
    id: "css-gradient-generator",
    name: "CSS 渐变与阴影",
    description: "线性与径向渐变设计、多层拟物阴影调校，一键生成 CSS 与 Tailwind 样式",
    category: "design",
    tags: ["css", "渐变", "gradient", "阴影", "box-shadow", "tailwind", "调色盘"],
    iconName: "Palette",
    status: "stable",
    component: lazy(() => import("./tools/design/CssGradientGenerator")),
  },
  {
    id: "qrcode-tool",
    name: "二维码生成与识别",
    description: "高清二维码生成、自定义配色与 Logo 嵌入，支持本地图片解析",
    category: "design",
    tags: ["qrcode", "二维码", "生成二维码", "扫描", "解析二维码", "识别"],
    iconName: "QrCode",
    status: "stable",
    component: lazy(() => import("./tools/design/QrCodeTool")),
  },
  {
    id: "barcode-tool",
    name: "条形码生成与识别",
    description: "支持 CODE128、EAN-13、UPC 等标准条形码生成下载与本地扫码识别",
    category: "design",
    tags: ["barcode", "条形码", "条码", "一维码", "code128", "ean13", "upc", "扫码"],
    iconName: "Barcode",
    status: "stable",
    component: lazy(() => import("./tools/design/BarcodeTool")),
  },
  {
    id: "svg-optimizer",
    name: "SVG 压缩优化",
    description: "清除 SVG 冗余元数据、缩短路径精度，导出轻量 SVG、DataURI 与 React 组件",
    category: "design",
    tags: ["svg", "svg压缩", "矢量图", "svg优化", "datauri", "react-icon", "svg2jsx"],
    iconName: "FileCode",
    status: "stable",
    component: lazy(() => import("./tools/design/SvgOptimizer")),
  },
  {
    id: "svg-path-editor",
    name: "SVG 路径编辑",
    description: "SVG Path 路径实时平移、缩放、水平/垂直翻转、坐标包围盒计算与代码导出",
    category: "design",
    tags: ["svg", "path", "svg变换", "路径平移", "路径缩放", "镜像翻转"],
    iconName: "Sparkles",
    status: "stable",
    component: lazy(() => import("./tools/design/SvgPathEditor")),
  },
  {
    id: "code-to-image",
    name: "代码截图卡片",
    description: "将代码片段一键生成高颜值 Ray.so / Carbon 风格分享卡片与高清 PNG 导出",
    category: "design",
    tags: ["代码截图", "code2img", "carbon", "ray.so", "代码美化", "分享卡片"],
    iconName: "Camera",
    status: "stable",
    component: lazy(() => import("./tools/design/CodeToImage")),
  },
  {
    id: "emoji-searcher",
    name: "Emoji 表情",
    description: "支持中文、拼音、英文模糊搜索与常用表情一键点击复制",
    category: "design",
    tags: ["emoji", "表情", "表情包", "符号", "颜文字", "emoticons"],
    iconName: "Smile",
    status: "stable",
    component: lazy(() => import("./tools/design/EmojiSearcher")),
  },

  // ── 6. 加密安全 (crypto) ──
  {
    id: "hash-calculator",
    name: "哈希散列计算",
    description: "聚合 MD5、SHA-1、SHA-256、SHA-512、SHA-3、RIPEMD160 等散列与 HMAC 计算",
    category: "crypto",
    tags: ["hash", "md5", "sha256", "sha512", "sha1", "hmac", "散列", "校验码", "摘要"],
    iconName: "Hash",
    status: "stable",
    component: lazy(() => import("./tools/crypto/HashCalculator")),
  },
  {
    id: "file-hash-checker",
    name: "文件哈希校验",
    description: "计算 SHA-256/SHA-1 校验指纹，比对官方校验签名或双文件内容一致性防篡改",
    category: "crypto",
    tags: ["文件比对", "文件哈希", "sha256校验", "完整性校验", "防篡改", "查重"],
    iconName: "ShieldCheck",
    status: "stable",
    component: lazy(() => import("./tools/crypto/FileHashChecker")),
  },
  {
    id: "symmetric-crypto",
    name: "对称加解密",
    description: "支持 AES、DES、3DES、RC4、Rabbit 与 SM4 对称加解密",
    category: "crypto",
    tags: ["aes", "des", "3des", "rc4", "sm4", "加密", "解密", "crypto", "cbc", "ecb"],
    iconName: "Lock",
    status: "stable",
    component: lazy(() => import("./tools/crypto/SymmetricCrypto")),
  },
  {
    id: "asymmetric-crypto",
    name: "非对称加解密",
    description: "支持 RSA (2048-bit) 与 SM2 密钥对生成、公钥加密与私钥解密",
    category: "crypto",
    tags: ["rsa", "sm2", "非对称", "公钥", "私钥", "加密", "解密", "密钥对", "keypair"],
    iconName: "KeyRound",
    status: "stable",
    component: lazy(() => import("./tools/crypto/AsymmetricCrypto")),
  },
  {
    id: "password-generator",
    name: "密码生成器",
    description: "基于密码学加密安全随机数生成高强度随机密码，支持批量与强度估算",
    category: "crypto",
    tags: ["密码", "密码生成", "随机密码", "password", "强密码", "安全密码"],
    iconName: "Dices",
    status: "stable",
    component: lazy(() => import("./tools/crypto/PasswordGenerator")),
  },
  {
    id: "uuid-generator",
    name: "UUID / NanoID 生成",
    description: "批量生成 UUID v4/v1、NanoID、ULID 等唯一标识符，支持大小写与 SQL/JSON 导出",
    category: "crypto",
    tags: ["uuid", "nanoid", "ulid", "cuid", "guid", "唯一标识", "随机id", "uuid生成"],
    iconName: "Fingerprint",
    status: "stable",
    component: lazy(() => import("./tools/crypto/UuidGenerator")),
  },
  {
    id: "short-url-tool",
    name: "短链接生成",
    description: "基于 Base62 / Base58 算法生成高压缩短网址 Slug 并支持还原与自定义域名",
    category: "crypto",
    tags: ["短链接", "shorturl", "base62", "base58", "短网址", "slug"],
    iconName: "Link2",
    status: "stable",
    component: lazy(() => import("./tools/crypto/ShortUrlTool")),
  },

  // ── 7. 多媒体 (media) ──
  {
    id: "audio-cutter",
    name: "音频剪辑",
    description: "Web Audio 绘制波形图、毫秒级区间裁剪、淡入淡出调节并导出无损 WAV 文件",
    category: "media",
    tags: ["音频剪辑", "波形图", "音频裁剪", "wav导出", "淡入淡出", "audio", "剪音乐"],
    iconName: "Volume2",
    status: "stable",
    component: lazy(() => import("./tools/media/AudioCutter")),
  },
  {
    id: "video-to-gif",
    name: "视频转 GIF",
    description: "纯本地读取视频文件，截取指定时间段、调节帧率与分辨率快速生成高质量 GIF",
    category: "media",
    tags: ["视频转gif", "gif制作", "动图生成", "录屏转gif", "video2gif"],
    iconName: "Film",
    status: "stable",
    component: lazy(() => import("./tools/media/VideoToGif")),
  },
  {
    id: "screen-tester",
    name: "屏幕检测",
    description: "全屏纯色坏点检测、四周漏光检测、256 级灰阶过渡与色阶均匀度测试",
    category: "media",
    tags: ["屏幕测试", "坏点检测", "漏光测试", "灰阶测试", "显示器测试", "screen"],
    iconName: "Monitor",
    status: "stable",
    component: lazy(() => import("./tools/media/ScreenTester")),
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}
